---
title: "Syllabus EC437/537 Winter 2017"
author: "James Woods"
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

The official description of the course is:

> Examines the rationale, economic principles and institutions of historic economic regulation. Contemporary theory of the firm and microeconomic pricing are analyzed. Technological changes suggest that to achieve economic efficiency it may no longer be necessary or appropriate to subject energy and telecommunications firms to traditional utility regulation. There is academic enthusiasm for displacing economic regulation with competition. Deregulation and restructuring are explored with emphasis on contemporary issues in Oregon, the Pacific Northwest, and the nation. In particular, difficulties in transformation to the marketplace will be examined. Expert guest lecturers from the utility and regulatory communities will be scheduled, and contemporary scholarly literature will be reviewed.

Since I am teaching this course for the first time, there will be changes from previous terms and I will be making official changes in description and prerequisites during the year.  

This is a companion course to EC 438/538 which will address the development of energy markets. The order of the courses has changed to reflect the evolving nature of the field.

## Prerequisites

The undergraduate section has only the introductory economics courses listed as prerequisites.  The graduate section requires only graduate standing.  

As with most economics courses, the more background you bring to the class, the more get from the class.  For this class, it means bringing a background in microeconomic theory and econometrics.  Not all students will have a background in both and many of the graduate students from outside of economics will have neither.  Any technical skills that students are missing will be supplemented with in-class tutorials.  Sometimes this will mean learning about constrained optimization or breaking out laptops for a tutorial on running regressions in R.

## Key Dates

+ First Issue Paper: Feb 1st
+ Midterm: Feb 9th
+ Last day to drop or change grade option: Feb 26th
+ Second Issue Paper: March 13th.
+ Final Exam: March 21st, 8am

# Contact Information

Communication will be handled through slack https://utilityeconwinter17.slack.com. You should have received an invitation, if not just go to that URL and use your @pdx.edu email to sign up. There are reasonable help documents to get you started. https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-users

Slack will be used for IM, email and forum style communication.  It even handles phone calls. If you have a question about course material or the course itself, ask in one of the channels. If you have a personal message that is not intended for others, send a direct message.

Please note that I am not online all the time and when I am online I will prioritize well phrased questions with sufficient detail.  I tend to ignore general complaints, questions that can be answered by reading the syllabus or using the search bar.  

Office Hours:

+ My office is in CH 241-O.
+ Drop in office hours are Tuesday 1:00-2:30pm  through the last week of class. There is no need to make an appointment for these hours -- just come.
+ If you can’t attend regular office hours, please check my calendar https://woodsj.youcanbook.me/. I will make a limited number of 20 minute slots available each week. If you make an appointment and fail to show up without first canceling, I will penalize your final exam score two points.  

Contact information and office hours for the teaching assistant will be posted on slack after the first week of class.  We will also post some hours where we will available interactively on slack.


# Textbook and Other Resources

The main text for the course is Lesser, Johnathan A. & Leonardo R. Giacchino. Fundamentals of Energy Regulation, ed 2. Public Utilities Fortnightly, 2013. It was chosen with undergraduates, and the previous focus on electricity, in mind and illustrates many of the concepts they learned in EC 311/415. 

This text will be supplemented with journal articles and books available electronically through the library.

# Assessments and Grade Policy

Your grade in the class will be based on your performance on homework assignments, two exams, and two issue papers on a regulatory topic.  

+ Final Exam (30%)
+ Midterm  (25%)
+ Issue Papers (20%)
+ Homework (25%)

## Homework

There will be several assignments over the term.  All will be equally weighted and are intended to be completed by an individual and turned into a dropbox in D2L. They will be graded on a 0-2 scale with 1 being the most common grade, 2 being exceptional and zero possible for substandard work. Simply turning in something does not automatically warrant a grade of 1.

## Issue Papers

The homework assignments are intended to be brief, technically contained, questions.  Issues papers are longer, more free-form, explorations of a regulatory issue of less than five pages in length.  There will be one prior to each exam.  They will be graded on a 0-5 scale with 3 being the most common grade and 5 being exceptional.  As with the homework, simply turning in something does not automatically warrant a grade of 1.

## Exams

Exams are open book and open note.  No electronic resources are allowed. If you want to bring electronic reserve material please bring your own printed copies.  Note that there is a limitation on the number of pages from the "Economics of Regulation and Antitrust" text that can be printed by each student. 

Because of the resources available, the exams will be *considerably* more difficult than the typical closed note and book exam.  Please prepare accordingly. The intent is to have exam questions be between homework and issue paper complexity but closer to homework.

# Topics and Readings

Do not let this section alarm you.  We will only address part of this outline in the class. As with most of my upper-division courses, we will complete a small subset at the start of the class and then vote on each succeeding topic. Each topic will have an assignment, usually working with real data or using a model from the readings.

Each topic has some readings that both undergraduates and graduate students will read and some that are specific to each. I will be adding topics and supplementary readings throughout the term.


+ Cost Theory Basis Regulation
    + Introduction. Ch 11, Viscusi, W. Kip, Joseph E. Harrington, and John M. Vernon. Economics of regulation and antitrust. MIT press, 2005. http://search.library.pdx.edu/PSU:psu_library:CP71189149050001451     
    + Lesser & Giacchino, Ch 2 (More small details on electricity than Viscusi and simpler theory)

+ Regulation and Public Enterprise
    + Efficiency and Technical Progress, Ch 4, Viscusi, et al (2005)
    + Theory of Natural Monopoly. Ch 10, Viscusi, et al (2005)
    + Public Enterprise. Ch 14, Viscusi, et al (2005)

+ Introduction to Electricity and Natural Gas
    + Lesser & Giacchino, Ch 1 (Good read on the history of gas and electic regulation)
    + Natural Monopoly Regulation and Electric Power,  Ch 12, Viscusi, et al (2005)
    + Economic Regulation of Energy, Ch 18, Viscusi, et al (2005)
    + Lesser & Giacchino, Ch 3 (More electicity specific details on Costs.)
    
+ Review of Basic Econometrics

+ Franchise Bidding, Dynamics and Deregulation
    + Franchise Bidding and Cable Television, Ch 13, Viscusi, et al (2005)
    + Dynamic Issues in Natural Monopoly Regulation, Ch 15, Viscusi, et al (2005)
    + Economic Regulation of Transportation, Ch 17, Viscusi, et al (2005)
    + Lesser & Giacchino, Ch 4

+ Deep Dive on Electricity (Under Construction)
    + Lesser & Giacchino, Ch 5, 6
    + Lesser & Giacchino, Ch 7, 8
        
+ Optional Topics
    + Lesser & Giacchino, Ch 9-13

# Other Rules

+ Begging for grades will result in an immediate lowering of your course grade by a full letter grade.
  
+ When completing assignments *The work must be authentically and genuinely your own or group. In other words, if you are copying answers you found online, it is not your work.*
  
+ Go to office hours at the first sign of trouble -- not as a last resort.

+ In this classroom, we support and value diversity.  To do so requires that we:

    + Respect the dignity and essential worth of all individuals
    + Promote a culture of respect toward all individuals
    + Respect the privacy, property, and freedom of others
    + Reject bigotry, discrimination, violence, or intimidation of any kind
    + Practice personal and academic integrity and expect it from others
    + Promote the diversity of opinions, ideas, and backgrounds, which is the lifeblood of a university

   For additional information, please see the Office of Affirmative Action \& Equal Opportunity at http://www.pdx.edu/diversity/affirmative-action.

+ Accommodations are collaborative efforts between students, faculty, and the Disability Resource Center.  If you have a documented disability and require accommodation, you must arrange to meet with the course instructor prior to or within the first week of the term.  The documentation of your disability must come in writing from the Disability Resource Center (Faculty letter).  Students who believe they are eligible for accommodations but who have not yet obtained approval through the DRC should contact the DRC immediately.  Reasonable and appropriate accommodations will be provided for students with documented disabilities.  For more information on the Disability Resource Center, please see http://www.drc.pdx.edu. 

+ Academic honesty is expected and required of students enrolled in this course.  Suspected academic dishonesty in this course will be handled according to the procedures set out in the Student Code of Conduct.

+ I am sympathetic to family emergencies but you must inform me as soon as possible. If the notice is verbal, please email me with your understanding of our agreement. All agreements have to be in writing.

Link to this syllabus https://github.com/woodsjam/Course-Public-Utility-Economics. Check branch for this term.

