---
title: "Syllabus EC437/537 Winter 2022"
author: "James Woods"
date: ''
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Course Description

The official description of the course is:

> Examines the rationale, economic principles, and institutions of historic economic regulation. Contemporary theory of the firm and regulatory practice with a focus on energy are analyzed. Prerequisites: Ec 311 or Ec 415. 

This is a companion course to EC 438/538 which will address the consequences of energy use and production, and EC 428/538, which is mainly focused on program evaluation, including energy conservation programs.

## Prerequisites


The undergraduate section has microeconomic theory, EC 311, or the calculus-based version, EC 415, listed as prerequisites.  The graduate section requires only graduate standing.


## Technology Requirements

You should have access to  Zoom and a functioning web browser to access Google tools.  We will primarily be using Docs and Jamboard, a shared whiteboard in the Google tools bundle. 

I will assume you have some touch or pseudo-pen interface. For example, you could use your finger and your phone (which works but I would not recommend. A small stylus works much better.), a computer with a touch screen, or even a small \$30 Wacom tablet.

The technology requirements are your responsibility. 

# Contact Information

We will handle course communication through slack <http://woodseconomics.slack.com/>. There is an invite link on the Canvas homepage for this course. Use your @pdx.edu email to sign up. There are reasonable help documents to get you started (<https://get.slack.help/hc/en-us/articles/218080037-Getting-started-for-new-users>)

Slack allows for IM and forum-style communication. It even handles phone and video calls. If you have a question about course material or the course itself, ask in one of the channels, e.g., \#public_general. If you have a personal message not intended for others, send a direct message to @woodsj.

Office Hours:

Office hours, where I or the GA, Roy, will be active on Slack to answer questions via text, voice, or video, are scattered throughout the week in the attempt to make at least one convenient for you.   I will respond on Slack at other times, but I will not respond immediately.

+ Monday 4-5 pm
+ Tuesday 11am- 1pm
+ Thursday 1-2 pm

You can type to us and make an audio-only call or a video one.  We are flexible.

# Textbook and Other Resources

The two primary texts for the course are:

+ Viscusi, W. Kip, et al. Economics of Regulation and Antitrust, Fourth Edition, MIT Press, 2005. ProQuest Ebook Central, https://ebookcentral-proquest-com.proxy.lib.pdx.edu/lib/psu/detail.action?docID=3338843.
+ Lesser, Johnathan A. & Leonardo R. Giacchino. Fundamentals of Energy Regulation, ed 2. Public Utilities Fortnightly, 2013. 

These will be supplemented with journal articles and books available electronically through the library.  Students have often found that sharing a copy of the Lesser and Giacchino text, which we use in the second half of the course, is effective. 

# The In-Class Experience

This class is remote, which means it is just like a regular class.  We talk. Ask questions.  Draw things on the whiteboard/Jamboard and interact on table reads.

I am implementing a version of the silent meeting, which, despite the name, is anything but silent.  You can read about it here (https://medium.com/swlh/the-silent-meeting-manifesto-v1-189e9e3487eb). It has proven itself effective in a variety of settings.

## Regular Lecture Days

I'll have Zoom up but will be using it primarily for audio. The in-class material will be a combination of Google slides, which I will share with you, a Jamboard for problem-solving that we can all use, and the accumulated table reads, a 5-6 page document described in detail elsewhere, for the day. This combination of tools should work better for those with slower computer processors and less memory. 

Any slides I share with you and stay synced automatically. There is no need for me to screen share.  This combination of tools makes it much easier to join by phone without running Zoom in the background.

## Table Read Documents

We all have experience with remote learning and experienced the general lack of productivity and engagement.  I can also tell you from my side that being on camera and trying to provide enough enthusiasm and energy for an entire class is exhausting. 

Rather than shaking my fist at the sky in frustration, I'm embracing the problem.

We will decide on the next reading about a week before the class meeting. After that, I will break up the assignment into reasonable chunks so that each student is only responsible for a page or two of the final table read.

Usually, two students will be assigned to each part of the outline.  I will share a Google Doc with you that describes your section of the document, with a link to the document if possible, and a few `must haves.`  I'm trying to avoid the problem of students skipping the complex parts, which is where the fun is, and focusing on the easy parts.

After reading the source paper or chapter, start working in the Google Doc I shared with you.  

You should summarize the arguments in your section, criticize those arguments, provide examples, links to background material or data, and references if needed.  

I will assemble what you have done in a single table read.  There will be multiple, anonymous versions of each section.

That is an important point. Your grade on the table read will be based on an anonymous class vote.  Those that created a more informative and helpful table read will get a higher grade than those that did not.  I will randomize this, so you are not always paired with the same student on every assignment.

Once class starts, we will start the table read, section by section.  Your job as a participant is to use the comment feature to ask pertinent questions, provide clarifying text, additional examples, etc.  You can also answer other students' questions and expand on the examples.

The intent of your participation is to improve the document and help other students understand the material. Therefore, a simple "I agree!" is not helpful. 

At the end of each section, we will vote on which of the options was most helpful.   These votes will determine the grade for table read creation.

You will also be evaluated on their contributions and participation in class as documented in the table read.  The GA and I will do this a few days after class to add material once you have had more time to think about the topic.

These table reads will remain available for the rest of the term and are good references for the exams.

We will play through a table read on the first day with this syllabus.

# Assessments and Grade Policy

Course grades will be determined by your performance as both a creator of table reads, your participation in those table reads, a midterm, and a final.  In short, except for the table read and Zoom, it is a traditional class setup.

The proportion of your grade from each task is defined below.  Please note that there is a distinction between the graduate and undergraduate sections.

Undergraduate:

+ Table Read Creation and Leadership: 25%
+ Table Read Participation: 25%
+ Midterm (Feb 3): 25%
+ Final (March 18, 12:30-2:20pm) : 25%

Graduate:

+ Table Read Creation and Leadership: 20%
+ Table Read Participation: 20%
+ Current Regulatory Topic Table Read: 10%
+ Midterm (Feb 3): 25%
+ Final (March 18, 12:30-2:20pm) : 25%

Graduate students will have total authorship of a table read on a current regulatory topic.  Instead of breaking apart one chapter or paper into smaller chunks, you will take multiple sources and create a briefing for the rest of the class with links to data, external documents that clarify, etc.  For example, if you are doing a table read recent innovations in community solar, you should link to sample tariffs and key PUC documents.  Don't worry; I will help you out with this.

## Exams

There is both a midterm and a final exam in this class. The questions will require you to synthesize what you have learned, compare and contrast, using models and data from multiple sources to support your argument.  

These are open-note, open-book exams. That should indicate that these are more difficult exams rather than easier than closed-note.  Don't expect every question to be a superficial burn through some math problems.  If you are familiar with Costa's levels of inquiry, these are level three questions.  

I will keep a document of potential questions pinned in Slack. It is in your best interest to prepare to answer those questions.  Preparation could be an outline or full text.  It is not a good idea to walk in cold and wing it.

I will share a Google doc and a Jamboard with you on exam day.  You should complete your work in those documents.  

If you need to include diagrams or mathematical derivations and don't want to spend the time typing or using the draw function, you can do those on paper, take a photo and embed them in the document, or use the Jamboard.  If you are using Jambord, indicate in the Google Doc indicate the page of the Jamboard, so I know where to look.

Exams measure individual performance.  The work you turn in should be authentically yours.  Communication between students during the exam is not allowed.


# Topics and Readings

+ Introduction to Regulation
    + Making Regulations, Ch 2, Viscusi, W. Kip, Joseph E. Harrington, and John M. Vernon. Economics of regulation and antitrust. MIT press, 2005. http://search.library.pdx.edu/PSU:psu_library:CP71189149050001451
    + Efficiency and Technical Progress, Ch 4, Viscusi, et al (2005)
    + Theory of Natural Monopoly, Ch 11 Viscusi, et al (2005)

+ Models of Regulation
    + Introduction to Economic Regulation, Ch 10, Viscusi, et al (2005)
    + Posner, Richard A. “Theories of Economic Regulation.” The Bell Journal of Economics and Management Science, vol. 5, no. 2, 1974, pp. 335–358. JSTOR, https://www-jstor-org.proxy.lib.pdx.edu/stable/3003113.
    + Stigler, George J. “The Theory of Economic Regulation.” The Bell Journal of Economics and Management Science, vol. 2, no. 1, 1971, pp. 3–21 (https://www-jstor-org.proxy.lib.pdx.edu/stable/3003160)
    + Peltzman, Sam. "Toward a more general theory of regulation." The Journal of Law and Economics 19.2 (1976): 211-240. https://www.jstor.org.proxy.lib.pdx.edu/stable/725163
    + Becker, Gary. “Toward a More General Theory of Regulation.” The Journal of Law & Economics, vol. 19, no. 2, 1976, pp. 245–248. https://www-jstor-org.proxy.lib.pdx.edu/stable/725165
    + Becker, Gary S. “A Theory of Competition Among Pressure Groups for Political Influence.” The Quarterly Journal of Economics, vol. 98, no. 3, 1983, pp. 371–400.https://www-jstor-org.proxy.lib.pdx.edu/stable/1886017.

    
+ Electricity and Natural Gas    
    + Lesser & Giacchino, Ch 1 (Good read on the history of gas and electric regulation)
    + Natural Monopoly Regulation and Electric Power, Ch 12, Viscusi, et al (2005)
    + Lesser & Giacchino, Ch 2 (More small details on electricity than Viscusi and simpler theory)
    + Lesser & Giacchino, Ch 3 (More electricity specific details on Costs.)


+ Cost Measurement
    + Lesser & Giacchino, Ch 5
    + Malko, J. Robert, and Robert Skinner. "Selecting a Capital Structure for a Regulated Electric Utility: Some Issues and Directions." The Electricity Journal 24.7 (2011): 49-56. http://stats.lib.pdx.edu/proxy.php?url=http://www.sciencedirect.com/science/article/pii/S1040619011001722
    + Example Disallowance, Trojan: Public Utility Commission of Oregon Order 08-487 https://apps.puc.state.or.us/orders/2008ords/08-487.pdf
    + Example Disallowance, Rolling Hills: Public Utility Commission of Oregon Order 08-548 https://apps.puc.state.or.us/orders/2008ords/08-554.pdf
    
+ Cost Allocation
    + Lesser & Giacchino, Ch 6
    + Uniform System of Accounts, 18 CFER Part 101 https://www.ecfr.gov/current/title-18/part-101
    + Electric Utility Cost Allocation Manual, National Association
of Regulatory Utility Commissioners (1992) http://pubs.naruc.org/pub/53A20BE2-2354-D714-5109-3999CB7043CE
    + Roth, Alvin E., and Robert E. Verrecchia. "The Shapley value as applied to cost allocation: a reinterpretation." Journal of Accounting Research (1979): 295-303. http://stats.lib.pdx.edu/proxy.php?url=https://www.jstor.org/stable/2490320
  

+ Rate setting
    + Lesser & Giacchino, Ch 7


Here are some options for graduate students to use for their current regulatory topic.  I will help with references once they make decisions on a topic.  

+ Community Choice
  + Faruqui, Ahmad, Mariko Geronimo Aydin, and John Higham. "Factors behind the formation of community choice aggregation." The Electricity Journal 33.10 (2020): 106862. https://stats.lib.pdx.edu/proxy.php?url=https://www.sciencedirect.com/science/article/abs/pii/S1040619020301548

+ Performance Based Regulation
  + Costello, Kenneth W. "How PBR can go wrong." The Electricity Journal 33.7 (2020): 106801. https://stats.lib.pdx.edu/proxy.php?url=https://www.sciencedirect.com/science/article/abs/pii/S1040619020300932

+ Evaluating residential PV tariffs. 
+ Energy storage in tariffs and ISOs
+ Evaluation of the CAISO energy imbalance market.
+ Transmission costs in ISO/RTO jurisdictions 
+ X-Inefficiency in Cost of Service Regulation



# Policy Statements from the University

+ **PSU Grading System Undergraduate**: http://pdx.smartcatalogiq.com/2021-2022/Bulletin/Undergraduate-Studies/Grading-System-for-Undergraduates 

+ **Drop/Withdraw Deadline**: http://pdx.smartcatalogiq.com/en/2021-2022/Bulletin/Academic-Calendar

+ **Academic Integrity**: Academic integrity is a vital part of the educational experience at PSU. Please see the PSU Student Code of Conduct for the university’s policy on academic dishonesty. A confirmed violation of that Code in this course may result in failure of the course.

+ **Incomplete Policy**: Students do not have a right to receive or demand an Incomplete grade. The option of assigning an Incomplete grade is at the discretion of the instructor when the following criteria are met. Eligibility Criteria:

  1.	Required satisfactory course completion/participation. 
  2.	Reasonable justification for the request. 
  3.	Incomplete grade is not a substitute for a poor grade. 
  4.	Written agreement. (See Incomplete Contract)
  5.	Resolving the Incomplete. 



+ **Student Services Disability Access Statement**: If you have, or think you may have, a disability that may affect your work in this class and feel you need accommodations, contact the Disability Resource Center to schedule an appointment and initiate a conversation about reasonable accommodations. The DRC is located in 116 Smith Memorial Student Union, 503-725-4150, drc@pdx.edu, https://www.pdx.edu/disability-resource-center/ .

+ **Safe Campus Statement**: Portland State University desires to create a safe campus for our students. As part of that mission, PSU requires all students to take the learning module entitled Creating a Safe Campus: Preventing Gender Discrimination, Sexual Harassment, Sexual Misconduct and Sexual Assault. If you or someone you know has been harassed or assaulted, you can find the appropriate resources on PSU’s Enrollment Management & Student Affairs: Sexual Prevention & Response website at http://www.pdx.edu/sexual-assault

+ **Student Food Security** :Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live, and believes this may affect their performance in the course, is urged to contact Committee for Improving Student Food Security for support at foodhelp@pdx.edu. Furthermore, please notify the professor if you are comfortable in doing so. This will enable her to provide any resources that she may possess.

+ **Title IX Reporting**: As an instructor, students frequently come to me for assistance in matters that are not related to the course material. Please be aware that PSU’s policies require instructors to report any instance of sexual harassment, sexual and relationship violence and/or other forms of prohibited discrimination to University Officials, who keep the information private. If you would rather share information about these experiences with a PSU staff member who does not have these reporting responsibilities and can keep the information confidential, please contact one of the following campus resources.
  + Confidential Advocates: 503.894.7982, or by scheduling online (for matters regarding sexual harassment and sexual and relationship violence)
  + Center for Student Health and Counseling (SHAC): 1880 SW 6th Ave, 503.725.2800
  + Student Legal Services: 1825 SW Broadway, (SMSU) M343, 503.725.4556 For more information, please complete the required student module Understanding Sexual Misconduct and Resources in D2L.
PSU Sexual Misconduct Response website gives you comprehensive information about how to support and/or report an incident. Please complete the required student module Understanding Sexual Misconduct and Resources, which provides information about PSU policy and resources.



+ **Cultural Resource Centers**: The Cultural Resource Centers (CRCs) create a student-centered inclusive environment that enriches the university experience. We honor diversity, explore social justice issues, celebrate cultural traditions, and foster student identities, success, and leadership. Our centers include the Multicultural Student Center, La Casa Latina Student Center, Native American Student & Community Center, Pan African Commons, Pacific Islander, Asian, Asian American Student Center and the Middle Eastern, North African, South Asian program. We provide student leadership, employment, and volunteer opportunities; student resources such as computer labs, event, lounge and study spaces; and extensive programming. All are welcome!


+ **Recording Technology Notice**: We will use technology for virtual meetings and recordings in this course. Our use of such technology is governed by FERPA, the Acceptable Use Policy and PSU’s Student Code of Conduct. A record of all meetings and recordings is kept and stored by PSU, in accordance with the Acceptable Use Policy and FERPA. Your instructor will not share recordings of your class activities outside of course participants, which include your fellow students, TAs/GAs/Mentors, and any guest faculty or community-based learning partners that we may engage with. You may not share recordings outside of this course. Doing so may result in disciplinary action. 

+ **Turnitin**: Students agree that by taking this course all required papers may be subject to submission for textual similarity review to Turnitin.com for the detection of plagiarism. All submitted papers will be included as source documents in the Turnitin.com reference database solely for the purpose of detecting plagiarism of such papers. Use of Turnitin.com page service is subject to the Usage Policy and Privacy Pledge posted on the Turnitin.com site. 


Link to this syllabus https://github.com/woodsjam/Course-Public-Utility-Economics/blob/master/SyllabusPublicUtility.pdf
