---
title: "Public Utility Economics"
output: beamer_presentation
theme: "Berlin"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## Plan for the Day

+ Walk through the syllabus
+ Walk through tools and resources
+ Take a pre-test
+ Talk a little about microeconomics as time permits

## Syllabus

+ You can find the syllabus here. (https://github.com/woodsjam/Course-Public-Utility-Economics/blob/master/SyllabusPublicUtility.pdf)

+ Almost all the slides will also be on github. (https://github.com/woodsjam/Course-Public-Utility-Economics)

+ Download them before each class if you like but they are not a substitute for coming to class.


## Course Description

> Examines the rationale, economic principles, and institutions of historic economic regulation. Contemporary theory of the firm and regulatory practice with a focus on energy are analyzed. Prerequisites: Ec 311 or Ec 415. 

+ Fundamental problem is preparation
    + Undergraduate Students
        + Typically had 201 or 311 but not econometrics
        + Often the 311 skills  are pretty weak.
    + Graduate Students
        + Typically have no background in economics
        + May have very strong math skills -- if they come from engineering.
  
## The Solution

Solution is to teach the microeconomics and econometrics needed to understand the material  -- but no more than that.



## Who Am I?

+ Ph.D. Economist, UC Davis
+ First generation college, like many of you.
+ Background in energy conservation and program evaluation consulting going back to the early 90s.
    + Projects were multidisciplinary. Rarely did a project not involve, economists, engineers and others.
    + I have steel toed boots.
+ Former:
    + Oregon HECC commissioner
    + Parkrose School Board Chair
    + Multiple non-profit boards
    + County Budget Committees
    + Legislative Candidate.
+ Hobbies: Painfully Stereotypical Portlander

    
## Warnings About Me

+ I'm Dyslexic.  If you see a slide without a typo -- be amazed.
+ I have a _very_ dark sense of humor.
+ I am very direct.


## Key Dates

+ Midterm: Feb 5th
+ Final Exam: *Thursday*, March 19	12:30-14:20.
+ Last Day to Withdraw or Change Grade Option: February 23rd.
+ Holiday: January 20th


## Contact Information

+ My office is in CH 241-O.
+ Drop in office hours are Monday 3:00 PM - 4:30 and Tuesday 9:00 AM - 10:30 AM through the last week of class.

I will also keep Slack up during office hours to answer questions.

## Slack

I avoid email since it is a trash heap and a constant distraction.

+ The class will use slack https://utilityeconw20.slack.com
+ Handles direct messages, forum style responses.
+ You should be able to sign up with your pdx.edu account
+ Can access via webpage, apps in Android and iOS.

## Hints on Slack

+ Prefer #general to direct messaging me.
    + Questions about course material is for #general
    + Questions about your grade or anything private is for @woodsj
+ Don't start and end with, "I got 7 but the key shows 245.  What did I do wrong?"
    + Show your work.  The fix is often a single parameter.
    + Give details about what you tried and how you are interpreting things.
    + Asking for general help, generally results in little help.
    + Get specific.
+ Provide full text of the question you are working on.

In short, make it easy for someone to help you.

## More Slack Hints

+ Don't impute motivation.  
+ Night before the exam?
    + I'm getting a good nights sleep -- you should too.
    + I tend to respond up until 5pm.
+ Set personal Do Not Disturb times.  It it defaults to 10pm -8am.


## Textbook and Other Resources

The main text for the course is Lesser, Johnathan A. & Leonardo R. Giacchino. Fundamentals of Energy Regulation, ed 2. Public Utilities Fortnightly, 2013.

+ Other material will be available through the library.  
+ Links are in the syllabus including the other textbook.

## Assessments and Grade Policy

Your grade in the class will be based on your performance on homework assignments and two exams.  


+ Final Exam (30%)
+ Midterm  (30%)
+ Homework (40%)


## Homework

+ Homework may also take the form of an in-class presentation on a course topic.
+ When written, will be due Sunday at 11:59pm on D2L to avoid confusion. 

## Exams

+ Open book and open note.  No electronic resources are allowed. 
+ I will bring copies of the textbooks  for you to consult.
+ Some questions will be computational and some will require essays.

Please bring a laptop to class on exam day. You will be submitting your exams on a Google doc that you write in class supplemented with paper diagrams and math.


## Question from Last Year

1. Suppose a utility has an old, 1910, coal generating plant that is on the historical registry. There are a few like this in real life. Given the cases and regulatory laws you have seen, which of the following actions would be allowed and why.
    + Convert the building from a generator to a substation.
    + Knock down the building a replace it with a modern Combined Cycle Natural Gas plant.
    + The city could seize it, without compensation, for public use as part of a museum.
    
## Lets try the Pre-Test

+ We are going to do this one question at a time.
+ Brief answers will be given today
+ Will guide how much microtheory we do in class.

## This Class is Small

+ Allows for a lot of customization.
+ Lets run the room, get names, and what you intend to get out of the course.
+ As time permits, look at the pre-test.

        